# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 13:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('nameApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2017, 11, 23, 13, 34, 57, 998707, tzinfo=utc)),
        ),
    ]
