# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 13:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('nameApp', '0002_auto_20171123_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicBands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='band',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2017, 12, 4, 13, 58, 9, 441943, tzinfo=utc)),
        ),
    ]
