# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 14:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('nameApp', '0004_auto_20171204_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2017, 12, 4, 14, 18, 50, 631844, tzinfo=utc)),
        ),
    ]
