# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 14:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('nameApp', '0005_auto_20171204_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicbands',
            name='BandID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='nameApp.Band'),
        ),
        migrations.AlterField(
            model_name='band',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2017, 12, 4, 14, 58, 30, 451369, tzinfo=utc)),
        ),
    ]
