# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 15:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('nameApp', '0006_auto_20171204_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicBand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='musicbands',
            name='BandID',
        ),
        migrations.AlterField(
            model_name='band',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2017, 12, 4, 15, 7, 51, 758032, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='MusicBands',
        ),
        migrations.AddField(
            model_name='band',
            name='BandID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='nameApp.MusicBand'),
        ),
    ]
