# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 15:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('nameApp', '0007_auto_20171204_1107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musicband',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='band',
            name='BandID',
        ),
        migrations.AddField(
            model_name='musicband',
            name='bandID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nameApp.Band'),
        ),
        migrations.AlterField(
            model_name='band',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2017, 12, 4, 15, 17, 5, 937152, tzinfo=utc)),
        ),
    ]
