# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 15:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('nameApp', '0009_auto_20171204_1125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musicband',
            options={'ordering': ('bandID',)},
        ),
        migrations.RemoveField(
            model_name='musicband',
            name='name',
        ),
        migrations.AlterField(
            model_name='band',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2017, 12, 4, 15, 34, 37, 496503, tzinfo=utc)),
        ),
    ]
