# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 15:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('nameApp', '0012_auto_20171204_1136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musicband',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='musicband',
            name='name',
            field=models.CharField(default=None, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='band',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2017, 12, 4, 15, 37, 40, 730826, tzinfo=utc)),
        ),
    ]
