# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 17:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('nameApp', '0019_auto_20171204_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2017, 12, 4, 17, 17, 24, 818664, tzinfo=utc)),
        ),
    ]
